# Generated by Django 3.1.7 on 2021-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
