# Generated by Django 3.1.7 on 2021-02-28 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.CharField(choices=[('MP', 'Mops'), ('PK', 'Pekines'), ('SH', 'Shpic')], default='MP', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='relation_date',
            field=models.DateField(default=datetime.date(2021, 2, 28)),
        ),
    ]
