# Generated by Django 3.1.7 on 2021-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('grade', models.CharField(choices=[('DR', 'Doctor'), ('SDR', 'Super-doctor'), ('MDR', 'Mega-doctor')], max_length=100)),
            ],
        ),
    ]
