# Generated by Django 3.1.7 on 2021-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='max_animal_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='min_animal_weight',
            field=models.IntegerField(default=0),
        ),
    ]
