# Generated by Django 3.1.7 on 2021-02-28 09:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210227_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_animal_race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MP', 'Mops'), ('PK', 'Pekines'), ('SH', 'Shpic')], default='MP', max_length=8),
        ),
    ]
