# Generated by Django 3.1.7 on 2021-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210228_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_animal_gender',
            field=models.CharField(choices=[('BITCH', 'Bitch'), ('DGG', 'Dog'), ('BOTH', 'Both')], default='BOTH', max_length=100),
        ),
    ]
