# Generated by Django 3.1.7 on 2021-02-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreationDate', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Race', models.CharField(choices=[('MP', 'Mops'), ('PK', 'Pekines'), ('SH', 'Shpic')], default='MP', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Grade', models.CharField(choices=[('DR', 'Doctor'), ('SDR', 'Super-doctor'), ('MDR', 'Mega-doctor')], default='DR', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.animal')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.doctor')),
            ],
        ),
    ]
