# Generated by Django 3.1.7 on 2021-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Race',
            field=models.CharField(choices=[('MP', 'Mops'), ('PK', 'Pekines'), ('SH', 'Shpic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Grade',
            field=models.CharField(choices=[('DR', 'Doctor'), ('SDR', 'Super-doctor'), ('MDR', 'Mega-doctor')], max_length=100),
        ),
    ]
